travis:
  secure:
    BINSTAR_TOKEN: u0jzTK7Qn2Mc2dclvgPJxd7T5PSVJywEVY7PNziCoOgQyIKCudedcGyooWWnJAhFyNo9G1Xh9NWveSOR5xUinj/Ghn1Wu/I8bo9isx8g04UNe4XmkcF2Lw/JpaizUJPDr2ucwNR+GkbX78K4B+bffyoXK4AGHTNPsmp4hdtOmkgdC6M5h9xIzI5UvlEcYnBVXGG9Xs/Tt64Cv47e6Vyd4ire4CJjwR4BvfNW0019rcAUSLkMmbP31NVSIRh+3EK+NATjBBLg4G7MrbL2N/Tm2GoZVPVWPi/FyWyzWcQrdlPlY3tmBis6WVMNyaOm0coi8whu0LvqxW+M0EWiqmdRaqXciX7bLZrJK7WO2+90FCrB7fwlxCDVWOjdyRkIvfe9FSApnd1rCUhLtIHJx7jps2YyU7n/4GrgNLGjvfjmoIqTGVgl0tOFpx3Hg92PKrxepAhoYHrdil1Mh5dqMHMQnlPjYNSSsPRA60mnyTkHqKeRvZlin7OduueailaclMEAHQu8c0WCmnetOFVjspz73f1znqwTwwvsON4s6uLyUNJWW4RjLyoMWn4eY/87oBQ2vRpeZEl8LtbfEnnc+U1jM21nzumrW2SnlWY/HK82GHXu1hnlUst1OUUwTifVVWov2FQibOHcxWQ+A6T5pByQt2LADlY6u2+2FRbbBf4W458=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
